GET https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlYTY0YmIzZjJhZjNjMzhlMmJlN2E0YjAwOGE0ZTBmMCIsIm5iZiI6MTcyMTQ5MzYwOC4yNjg1NjUsInN1YiI6IjY2OWJlMjA1NWMwMGYyN2Q1MDA1ZDdmZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.RAREQr0-so21fgnTiU9QsIdHd5MpBXPUfVHh_ytDft0
accept: application/json
